- hosts: 127.0.0.1
  become: no
  connection: local
  roles:
    - download

- hosts: Controller, Worker, Ingress
  gather_facts: yes
  become: true
  roles:
    - basic
    - hosts
    - sshforuser
    - k8s-client

# K8s ingress nodes
- hosts: Ingress
  become: true
  gather_facts: "no"
  roles:
    - ingress
    - kubeproxy-certs

#K8S master controller
- hosts: Controller
  become: true
  gather_facts: "no"
  roles:
    - master-node
    - encryption
    - etcd
    - kubemasters
    - k8sroles

# workers nodes
- hosts: Worker
  become: true
  gather_facts: "no"
  roles:
    - workers