---
- hosts: controllers
  become: true
  roles:
    - basic
    - hostnames
    - basic-master
  vars:
#
- hosts: kubelets
  become: true
  roles:
    - basic
    - hostnames
  vars:
# ingress controller section
- hosts: ingress
  become: true
  roles:
    - hostnames
    - ingress
    - k8scerts
  vars:
